# Generated by Django 5.2.7 on 2025-12-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_factura_saldo_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
