# Generated by Django 5.2.7 on 2025-12-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_factura_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
